version: '3'

services:
  node:
    build:
      context: ./
      dockerfile: docker/node/Dockerfile
    command: yarn start
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./:/app:cached
